# Generated by Django 5.1.5 on 2025-04-13 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'verbose_name': 'علاقمند', 'verbose_name_plural': 'علاقمندی ها'},
        ),
    ]
