# Generated by Django 5.1.5 on 2025-06-03 16:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0011_product_discount_price_product_is_on_sale_and_more'),
        ('orders', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Discount Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED_AMOUNT', 'Fixed Amount')], max_length=20, verbose_name='Discount Type')),
                ('value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g., 10 for 10%) or fixed amount.', max_digits=10, verbose_name='Value')),
                ('code', models.CharField(blank=True, help_text='Coupon code. Leave blank for automatic discounts.', max_length=50, null=True, unique=True, verbose_name='Coupon Code')),
                ('active_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Active From')),
                ('active_until', models.DateTimeField(blank=True, null=True, verbose_name='Active Until')),
                ('minimum_cart_value', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum cart total for discount to apply.', max_digits=10, null=True, verbose_name='Minimum Cart Value')),
                ('applies_to', models.CharField(choices=[('ENTIRE_ORDER', 'Entire Order'), ('SPECIFIC_PRODUCTS', 'Specific Products'), ('SPECIFIC_CATEGORIES', 'Specific Categories')], default='ENTIRE_ORDER', max_length=20, verbose_name='Applies To')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maximum total uses for this discount.', null=True, verbose_name='Maximum Uses')),
                ('uses_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Times Used')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('categories', models.ManyToManyField(blank=True, help_text="Select categories if 'Applies To' is 'Specific Categories'.", to='main.category', verbose_name='Applicable Categories')),
                ('products', models.ManyToManyField(blank=True, help_text="Select products if 'Applies To' is 'Specific Products'.", to='main.product', verbose_name='Applicable Products')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
        migrations.CreateModel(
            name='AppliedDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_saved', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Saved')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Applied At')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_discounts_records', to='orders.order', verbose_name='Order')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discounts.discount', verbose_name='Discount Applied')),
            ],
            options={
                'verbose_name': 'Applied Discount Record',
                'verbose_name_plural': 'Applied Discount Records',
            },
        ),
    ]
