# Generated by Django 5.1.5 on 2025-06-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='is_automatic',
            field=models.BooleanField(default=False, help_text='Apply automatically without coupon code', verbose_name='Automatic Discount'),
        ),
    ]
