# Generated by Django 5.1.5 on 2025-02-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "کاربر ", "verbose_name_plural": "کاربران "},
        ),
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="نام کاربر"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="تاریخ تولد"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="ایمیل"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="کارمند"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="تایید ایمیل"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="شماره تلفن"
            ),
        ),
    ]
