# Generated by Django 5.1.5 on 2025-02-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                upload_to="product_images", verbose_name="تصویر محصول"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=1, max_digits=12, verbose_name="قیمت"
            ),
        ),
    ]
