# Generated by Django 5.1.5 on 2025-02-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_product_image_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                max_length=200,
                unique=True,
                verbose_name="آدرس یکتا",
            ),
        ),
    ]
