# Generated by Django 5.1.5 on 2025-02-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(verbose_name="قیمت"),
        ),
    ]
