# Generated by Django 5.1.5 on 2025-02-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_rating_options_remove_category_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
