# Generated by Django 5.1.5 on 2025-05-22 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_comment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_gallery_images', verbose_name='تصویر گالری محصول')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='main.product')),
            ],
            options={
                'verbose_name': 'تصویر گالری محصول',
                'verbose_name_plural': 'تصاویر گالری محصول',
            },
        ),
    ]
