# Generated by Django 5.1.5 on 2025-06-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_product_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت تخفیف'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(default=False, verbose_name='در تخفیف'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='پایان تخفیف'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='شروع تخفیف'),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
