# Generated by Django 5.1.5 on 2025-06-04 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_product_discount_price_product_is_on_sale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_on_sale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_end',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_start',
        ),
    ]
